;; xah-math-input everywhere
:*?oc:``nbsp:: 
:*?oc:``bull::•
:*?oc:``iexcl::¡
:*?oc:``cent::¢
:*?oc:``pound::£
:*?oc:``curren::¤
:*?oc:``yen::¥
:*?oc:``brvbar::¦
:*?oc:``sect::§
:*?oc:``uml::¨
:*?oc:``copy::©
:*?oc:``ordf::ª
:*?oc:``laquo::«
:*?oc:``Not::¬
:*?oc:``reg::®
:*?oc:``macr::¯
:*?oc:``deg::°
:*?oc:``plusmn::±
:*?oc:``sup2::²
:*?oc:``sup3::³
:*?oc:``acute::´
:*?oc:``micro::µ
:*?oc:``para::¶
:*?oc:``middot::·
:*?oc:``cedil::¸
:*?oc:``sup1::¹
:*?oc:``ordm::º
:*?oc:``raquo::»
:*?oc:``frac14::¼
:*?oc:``frac12::½
:*?oc:``frac34::¾
:*?oc:``iquest::¿
:*?oc:``Agrave::À
:*?oc:``Aacute::Á
:*?oc:``Acirc::Â
:*?oc:``Atilde::Ã
:*?oc:``Auml::Ä
:*?oc:``Aring::Å
:*?oc:``AElig::Æ
:*?oc:``Ccedil::Ç
:*?oc:``Egrave::È
:*?oc:``Eacute::É
:*?oc:``Ecirc::Ê
:*?oc:``Euml::Ë
:*?oc:``Igrave::Ì
:*?oc:``Iacute::Í
:*?oc:``Icirc::Î
:*?oc:``Iuml::Ï
:*?oc:``ETH::Ð
:*?oc:``Ntilde::Ñ
:*?oc:``Ograve::Ò
:*?oc:``Oacute::Ó
:*?oc:``Ocirc::Ô
:*?oc:``Otilde::Õ
:*?oc:``Ouml::Ö
:*?oc:``Oslash::Ø
:*?oc:``Ugrave::Ù
:*?oc:``Uacute::Ú
:*?oc:``Ucirc::Û
:*?oc:``Uuml::Ü
:*?oc:``Yacute::Ý
:*?oc:``Thorn::Þ
:*?oc:``szlig::ß
:*?oc:``agrave::à
:*?oc:``aacute::á
:*?oc:``acirc::â
:*?oc:``atilde::ã
:*?oc:``auml::ä
:*?oc:``aring::å
:*?oc:``aelig::æ
:*?oc:``ccedil::ç
:*?oc:``egrave::è
:*?oc:``eacute::é
:*?oc:``ecirc::ê
:*?oc:``euml::ë
:*?oc:``igrave::ì
:*?oc:``iacute::í
:*?oc:``icirc::î
:*?oc:``iuml::ï
:*?oc:``eth::ð
:*?oc:``ntilde::ñ
:*?oc:``ograve::ò
:*?oc:``oacute::ó
:*?oc:``ocirc::ô
:*?oc:``otilde::õ
:*?oc:``ouml::ö
:*?oc:``ugrave::ù
:*?oc:``uacute::ú
:*?oc:``ucirc::û
:*?oc:``uuml::ü
:*?oc:``yacute::ý
:*?oc:``thorn::þ
:*?oc:``yuml::ÿ
:*?oc:``OElig::Œ
:*?oc:``oelig::œ
:*?oc:``Scaron::Š
:*?oc:``scaron::š
:*?oc:``Yuml::Ÿ
:*?oc:``Alpha::Α
:*?oc:``Beta::Β
:*?oc:``Gamma::Γ
:*?oc:``Delta::Δ
:*?oc:``Epsilon::Ε
:*?oc:``Zeta::Ζ
:*?oc:``Eta::Η
:*?oc:``bigO::Θ
:*?oc:``Iota::Ι
:*?oc:``Kappa::Κ
:*?oc:``Lambda::Λ
:*?oc:``Mu::Μ
:*?oc:``Nu::Ν
:*?oc:``Xi::Ξ
:*?oc:``Omicron::Ο
:*?oc:``Pi::Π
:*?oc:``Rho::Ρ
:*?oc:``Sigma::Σ
:*?oc:``Tau::Τ
:*?oc:``Upsilon::Υ
:*?oc:``Phi::Φ
:*?oc:``Chi::Χ
:*?oc:``Psi::Ψ
:*?oc:``Omega::Ω
:*?oc:``alpha::α
:*?oc:``beta::β
:*?oc:``gamma::γ
:*?oc:``delta::δ
:*?oc:``epsilon::ε
:*?oc:``zeta::ζ
:*?oc:``AA::𝔸
:*?oc:``eta::η
:*?oc:``BB::𝔹
:*?oc:``theta::θ
:*?oc:``CC::ℂ
:*?oc:``iota::ι
:*?oc:``DD::𝔻
:*?oc:``kappa::κ
:*?oc:``EE::𝔼
:*?oc:``lambda::λ
:*?oc:``FF::𝔽
:*?oc:``mu::μ
:*?oc:``GG::𝔾
:*?oc:``nu::ν
:*?oc:``HH::ℍ
:*?oc:``xi::ξ
:*?oc:``II::𝕀
:*?oc:``omicron::ο
:*?oc:``JJ::𝕁
:*?oc:``pi::π
:*?oc:``KK::𝕂
:*?oc:``rho::ρ
:*?oc:``LL::𝕃
:*?oc:``fsigma::ς
:*?oc:``MM::𝕄
:*?oc:``sigma::σ
:*?oc:``NN::ℕ
:*?oc:``tau::τ
:*?oc:``OO::𝕆
:*?oc:``upsilon::υ
:*?oc:``phi::φ
:*?oc:``PP::ℙ
:*?oc:``chi::χ
:*?oc:``QQ::ℚ
:*?oc:``psi::ψ
:*?oc:``RR::ℝ
:*?oc:``omega::ω
:*?oc:``SS::𝕊
:*?oc:``Theta2::ϑ
:*?oc:``TT::𝕋
:*?oc:``upsih::ϒ
:*?oc:``UU::𝕌
:*?oc:``piv::ϖ
:*?oc:``VV::𝕍
:*?oc:``ndash::–
:*?oc:``WW::𝕎
:*?oc:``mdash::—
:*?oc:``XX::𝕏
:*?oc:``lsquo::‘
:*?oc:``YY::𝕐
:*?oc:``rsquo::’
:*?oc:``ZZ::ℤ
:*?oc:``dd::ⅆ
:*?oc:``sbquo::‚
:*?oc:``ee::ⅇ
:*?oc:``ldquo::“
:*?oc:``ii::ⅈ
:*?oc:``rdquo::”
:*?oc:``bdquo::„
:*?oc:``jj::ⅉ
:*?oc:``lsaquo::‹
:*?oc:``nat::ℕ
:*?oc:``integer::ℤ
:*?oc:``rsaquo::›
:*?oc:``dagger::†
:*?oc:``rational::ℚ
:*?oc:``dagger2::‡
:*?oc:``real::ℝ
:*?oc:``complex::ℂ
:*?oc:``hellip::…
:*?oc:``permil::‰
:*?oc:``quaternion::ℍ
:*?oc:``prime::′
:*?oc:``sedenion::𝕊
:*?oc:``prime2::″
:*?oc:``foot::′
:*?oc:``inch::″
:*?oc:``oline::‾
:*?oc:``frasl::⁄
:*?oc:``euro::€
:*?oc:``trade::™
:*?oc:``image::ℑ
:*?oc:``weierp::℘
:*?oc:``real::ℜ
:*?oc:``larr::←
:*?oc:``uarr::↑
:*?oc:``rarr::→
:*?oc:``darr::↓
:*?oc:``harr::↔
:*?oc:``crarr::↵
:*?oc:``lArr::⇐
:*?oc:``uArr::⇑
:*?oc:``rArr::⇒
:*?oc:``dArr::⇓
:*?oc:``hArr::⇔
:*?oc:``times::×
:*?oc:``divide::÷
:*?oc:``minus::−
:*?oc:``lowast::∗
:*?oc:``radic::√
:*?oc:``oplus::⊕
:*?oc:``otimes::⊗
:*?oc:``oslash::ø
:*?oc:``fnof::ƒ
:*?oc:``circ::ˆ
:*?oc:``tilde::˜
:*?oc:``nabla::∇
:*?oc:``part::∂
:*?oc:``exist::∃
:*?oc:``and::∧
:*?oc:``or::∨
:*?oc:``there4::∴
:*?oc:``isin::∈
:*?oc:``notin::∉
:*?oc:``ni::∋
:*?oc:``prod::∏
:*?oc:``sum::∑
:*?oc:``int::∫
:*?oc:``cap::∩
:*?oc:``cup::∪
:*?oc:``infin::∞
:*?oc:``prop::∝
:*?oc:``angel::∠
:*?oc:``sim::∼
:*?oc:``cong::≅
:*?oc:``asymp::≈
:*?oc:``ne::≠
:*?oc:``equiv::≡
:*?oc:``le::≤
:*?oc:``ge::≥
:*?oc:``sub::⊂
:*?oc:``sup0::⊃
:*?oc:``nsub::⊄
:*?oc:``Sube::⊆
:*?oc:``supe::⊇
:*?oc:``perp::⊥
:*?oc:``sdot::⋅
:*?oc:``lceil::⌈
:*?oc:``rceil::⌉
:*?oc:``lfloor::⌊
:*?oc:``rfloor::⌋
:*?oc:``lang::〈
:*?oc:``rang::〉
:*?oc:``loz::◊
:*?oc:``spades::♠
:*?oc:``clubs::♣
:*?oc:``hearts::♥
:*?oc:``diams::♦
;; accent
:*?oc:a``::à
:*?oc:e``::è
:*?oc:i``::ì
:*?oc:o``::ò
:*?oc:u``::ù
:*?oc:A``::À
:*?oc:E``::È
:*?oc:I``::Ì
:*?oc:O``::Ò
:*?oc:U``::Ù
:*?oc:``a^::â
:*?oc:``e^::ê
:*?oc:``i^::î
:*?oc:``o^::ô
:*?oc:``u^::û
:*?oc:``A^::Â
:*?oc:``E^::Ê
:*?oc:``I^::Î
:*?oc:``O^::Ô
:*?oc:``U^::Û
:*?oc:``a'::á
:*?oc:``e'::é
:*?oc:``i'::í
:*?oc:``o'::ó
:*?oc:``u'::ú
:*?oc:``y'::ý
:*?oc:``A'::Á
:*?oc:``E'::É
:*?oc:``I'::Í
:*?oc:``O'::Ó
:*?oc:``U'::Ú
:*?oc:``Y'::Ý
:*?oc:``A\::Ä
:*?oc:``E\::Ë
:*?oc:``I\::Ï
:*?oc:``O\::Ö
:*?oc:``U\::Ü
:*?oc:``a\::ä
:*?oc:``e\::ë
:*?oc:``i\::ï
:*?oc:``o\::ö
:*?oc:``u\::ü
:*?oc:``s\::ß
:*?oc:``y\::ÿ
:*?oc:``Ao::Å
:*?oc:``ao::å
:*?oc:``AE::Æ
:*?oc:``ae::æ
:*?oc:``a~::ã
:*?oc:``n~::ñ
:*?oc:``o~::õ
:*?oc:``A~::Ã
:*?oc:``N~::Ñ
:*?oc:``O~::Õ
:*?oc:``tm::™
:*?oc:``3/4::¾
:*?oc:``1/2::½
:*?oc:``1/4::¼
:*?oc:``...::…
:*?oc:``fdash::‒
:*?oc:``wdash::〜
:*?oc:``--::—
:*?oc:``??::﻿¿
:*?oc:``?!::⁈
:*?oc:``!?::⁉
:*?oc:``!!::﻿¡
:*?oc:``nno::№
:*?oc:^_^::😄
:*?oc:^_^'::😅
:*?oc:``>_<::😆
:*?oc:``¬_¬::😒
:*?oc:``meh::😒
:*?oc:``obj::￼
:*?oc:``:o::😮
:*?oc:``:O::😲
:*?oc:``smile::☺
:*?oc:``:)::☺
:*?oc:``:D::☺
:*?oc:``:/::😕
:*?oc:``:P::😋
:*?oc:``:(::☹
:*?oc:``;)::😉
:*?oc:``wink::😉
:*?oc:``cry::😢
:*?oc:``sad::☹
:*?oc:``good::👍
:*?oc:``bad::👎
:*?oc:``ok::👌
:*?oc:``fist::👊
:*?oc:``tv::📺
;;unicode computing
:*?oc:``cmd::⌘
:*?oc:``opt::⌥
:*?oc:``alt::⎇
:*?oc:``ctrl::✲
:*?oc:``helm::⎈
:*?oc:``caret::‸
:*?oc:``menu::▤
:*?oc:``shift::⇧
:*?oc:``enter::⌤
:*?oc:``return::⏎
:*?oc:``pgup::⇞
:*?oc:``pgdn::⇟
:*?oc:``prevpage::⎗
:*?oc:``nextpage::⎘
:*?oc:``home::↖
:*?oc:``end::↘
:*?oc:``Esc::⎋
:*?oc:``eject::⏏
:*?oc:``undo::⎌
:*?oc:``redo::↷
:*?oc:``backspace::⌫
:*?oc:``delete::⌦
:*?oc:``space::␣
:*?oc:``tab::↹
:*?oc:``tabl::⇤
:*?oc:``tabr::⇥
:*?oc:``|<-::⇤
:*?oc:``->|::⇥
:*?oc:``lrarr::⇄
:*?oc:``sleep::☾
:*?oc:``break::⎊
:*?oc:``pause::⎉
:*?oc:``print::⎙
:*?oc:``keyboard::⌨
:*?oc:``clear::⌧
:*?oc:``cursor::▮
:*?oc:``ibeam::⌶
:*?oc:``watch::⌚
:*?oc:``hourglass::⌛
:*?oc:``scissor::✂
:*?oc:``envelope::✉
:*?oc:``write::✍
;;unicode astronomy::
:*?oc:``Sun::☉
:*?oc:``sunray::☼
:*?oc:``Moon::☾
:*?oc:``moonr::☽
:*?oc:``mercury::☿
:*?oc:``earth::♁
:*?oc:``saturn::♄
:*?oc:``uranus::♅
:*?oc:``neptune::♆
:*?oc:``pluto::♇
:*?oc:``jupiter::♃
:*?oc:``male::♂
:*?oc:``mars::♂
:*?oc:``female::♀
:*?oc:``venus::♀
:*?oc:``comet::☄
;;superscripts::
:*?oc:``^0::⁰
:*?oc:``^1::¹
:*?oc:``^2::²
:*?oc:``^3::³
:*?oc:``^4::⁴
:*?oc:``^5::⁵
:*?oc:``^6::⁶
:*?oc:``^7::⁷
:*?oc:``^8::⁸
:*?oc:``^9::⁹
:*?oc:``^+::⁺
:*?oc:``^-::⁻
:*?oc:``^=::⁼
:*?oc:``^(::⁽
:*?oc:``^)::⁾
:*?oc:``^n::ⁿ
:*?oc:``^i::ⁱ
;;subscripts::
:*?oc:``_(::₍
:*?oc:``_)::₎
:*?oc:``_+::₊
:*?oc:``_-::₋
:*?oc:``_0::₀
:*?oc:``_1::₁
:*?oc:``_2::₂
:*?oc:``_3::₃
:*?oc:``_4::₄
:*?oc:``_5::₅
:*?oc:``_6::₆
:*?oc:``_7::₇
:*?oc:``_8::₈
:*?oc:``_9::₉
:*?oc:``_=::₌
:*?oc:``_a::ₐ
:*?oc:``_e::ₑ
:*?oc:``_h::ₕ
:*?oc:``_i::ᵢ
:*?oc:``_j::ⱼ
:*?oc:``_k::ₖ
:*?oc:``_l::ₗ
:*?oc:``_m::ₘ
:*?oc:``_n::ₙ
:*?oc:``_o::ₒ
:*?oc:``_p::ₚ
:*?oc:``_r::ᵣ
:*?oc:``_s::ₛ
:*?oc:``_t::ₜ
:*?oc:``_u::ᵤ
:*?oc:``_v::ᵥ
:*?oc:``_x::ₓ
:*?oc:``_schwa::ₔ
;;more math
:*?oc:``inf::∞
:*?oc:``empty::∅
:*?oc:``es::∅
:*?oc:``+-::±
:*?oc:``-+::∓
:*?oc:``flr::⌊⌋
:*?oc:``ceil::⌈⌉
:*?oc:``floor::⌊⌋
:*?oc:``ceiling::⌈⌉
:*?oc:``""::“”
:*?oc:``<>::‹›
:*?oc:``<<>>::«»
:*?oc:``[::「」
:*?oc:``[]::「」
:*?oc:``[[::『』
:*?oc:``[[]]::『』
:*?oc:``[(::【】
:*?oc:``[()]::【】
:*?oc:``(::〔〕
:*?oc:``()::〔〕
;; time
:*?oc:``1:30::🕜
:*?oc:``2:00::🕑
:*?oc:``2:30::🕝
:*?oc:``3:00::🕒
:*?oc:``3:30::🕞
:*?oc:``4:00::🕓
:*?oc:``4:30::🕟
:*?oc:``5:00::🕔
:*?oc:``5:30::🕠
:*?oc:``6:00::🕕
:*?oc:``6:30::🕡
:*?oc:``7:00::🕖
:*?oc:``7:30::🕢
:*?oc:``8:00::🕗
:*?oc:``8:30::🕣
:*?oc:``9:00::🕘
:*?oc:``9:30::🕤
:*?oc:``10:00::🕙
:*?oc:``10:30::🕥
:*?oc:``11:00::🕚
:*?oc:``11:30::🕦
:*?oc:``12:00::🕛
:*?oc:``12:30::🕧
;; greek letter::
:*?oc:``ga::α
:*?oc:``gb::β
:*?oc:``gg::γ
:*?oc:``gd::δ
:*?oc:``ge::ε
:*?oc:``gz::ζ
:*?oc:``gh::η
:*?oc:``gq::θ
:*?oc:``gi::ι
:*?oc:``gk::κ
:*?oc:``gl::λ
:*?oc:``gm::μ
:*?oc:``gn::ν
:*?oc:``gp::π
:*?oc:``gr::ρ
:*?oc:``gs::σ
:*?oc:``gt::τ
:*?oc:``gv::υ
:*?oc:``gf::φ
:*?oc:``gy::ψ
:*?oc:``go::ω
:*?oc:``gA::Α
:*?oc:``gB::Β
:*?oc:``gG::Γ
:*?oc:``gD::Δ
:*?oc:``gE::Ε
:*?oc:``gZ::Ζ
:*?oc:``gH::Η
:*?oc:``gQ::Θ
:*?oc:``gI::Ι
:*?oc:``gK::Κ
:*?oc:``gL::Λ
:*?oc:``gM::Μ
:*?oc:``gN::Ν
:*?oc:``gX::Ξ
:*?oc:``gP::Π
:*?oc:``gR::Ρ
:*?oc:``gS::Σ
:*?oc:``gT::Τ
:*?oc:``gV::Υ
:*?oc:``gF::Φ
:*?oc:``gY::Ψ
:*?oc:``gO::Ω
;;letter-likeforms::
:*?oc:``alef::ℵ
:*?oc:``beth::ב
:*?oc:``gimel::ג
:*?oc:``dalet::ד
:*?oc:``daleth::ד
:*?oc:``Digamma::Ϝ
:*?oc:``digamma::ϝ
:*?oc:``wp::℘
:*?oc:``angstrom::Å
:*?oc:``R2::ℝ²
:*?oc:``R3::ℝ³
:*?oc:``fn::ƒ
;;relationshttp://xahlee.info/comp/unicode_math_operators.html::
:*?oc:``!<::≺
:*?oc:``!>::≻
:*?oc:``<=::≤
:*?oc:``>=::≥
:*?oc:``!el::∉
:*?oc:``el::∈
:*?oc:``&&::∧
:*?oc:``||::∨
:*?oc:``Not::¬
:*?oc:``===::≡
:*?oc:``Xor::⊻
:*?oc:``Nand::⊼
:*?oc:``Nor::⊽
:*?oc:``~::≈
:*?oc:``:=::≔
:*?oc:``=:::≕
:*?oc:``!=::≠
:*?oc:``fa::∀
:*?oc:``forall::∀
:*?oc:``ex::∃
:*?oc:``tack::⊢
:*?oc:``tee::⊢
:*?oc:``|-::⊢
:*?oc:``-|::⊣
;; unicode arrows::
:*?oc:``<-::←
:*?oc:``->::→
:*?oc:``<->::↔
:*?oc:``!<-::↚
:*?oc:``!->::↛
:*?oc:``!<->::↮
:*?oc:``≤::⇐
:*?oc:``=>::⇒
:*?oc:``<=>::⇔
:*?oc:``!<=::⇍
:*?oc:``!=>::⇏
:*?oc:``!=>::⇎
:*?oc:``<==::⟸
:*?oc:``==>::⟹
:*?oc:``<==>::⟺
:*?oc:``<-|::↤
:*?oc:``|->::↦
:*?oc:``<--::⟵
:*?oc:``-->::⟶
:*?oc:``<-->::⟷
;;operators::
:*?oc:``c+::⊕
:*?oc:``c*::⊗
:*?oc:``c-::⊖
:*?oc:``c/::⊘
:*?oc:``'::′
:*?oc:``''::″
:*?oc:``'''::‴
:*?oc:``.::·
:*?oc:``root::√
:*?oc:``sqrt::√
:*?oc:``rt::√
:*?oc:``Del::∇
:*?oc:``part::∂
:*?oc:``partial::∂
:*?oc:``pd::∂
:*?oc:``cross::⨯
:*?oc:``cint::∮
:*?oc:``ccint::∲
:*?oc:``cccint::∳
:*?oc:``union::∪
:*?oc:``Intersec::∩
:*?oc:``/_::∠
:*?oc:``rightangle::⦜
:*?oc:``|_::⦜
:*?oc:``triangle::▲
:*?oc:``tril::◀
:*?oc:``trir::▶
:*?oc:``trid::▼
:*?oc:``square::■
:*?oc:``circle::●
:*?oc:``<3::♥
;; more xah-math-input
;; Gothic, Double Struck http://xahlee.info/math/math_font_unicode.html